# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/ruoyi-modules-danny.jar /home/ruoyi/ruoyi-modules-danny.jar

#安装字体文件 解决在linux下bpmn图片字体显示方框问题 
COPY simsun.ttc /usr/share/fonts/
RUN yum -y install fontconfig
RUN fc-list

# 启动系统服务
ENTRYPOINT ["java","-jar","ruoyi-modules-danny.jar"]